### ISSUE TITLE
[BUG] 500 HttpException Version 4.9.2

### ISSUE THREAD

**Issue by Shadow27374** [linuxserver/docker-lychee#67]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

500 HttpException
Target class [log-viewer] does not exist.

### Steps To Reproduce

image: ghcr.io/linuxserver/lychee:4.9.2

### Environment

```markdown
- OS: Ubuntu Server 22.04.02 LTS
```

### CPU architecture

x86-64

### Docker creation

```bash
lychee:
    image: ghcr.io/linuxserver/lychee:4.9.2
    #image: ghcr.io/linuxserver/lychee:latest
    container_name: lychee
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lychee.rule=Host(`xxxxxxxxxxxxxxxxxxxxxx`)"
      - "traefik.http.routers.lychee.middlewares=secured@file"
      - "traefik.http.routers.lychee.tls=true"
    volumes:
      - /home/sysadmin/docker/lychee/config:/config
      - /home/sysadmin/docker/lychee/pictures:/pictures
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=lychee
      - DB_PASSWORD=xxxxxxxxxxxxxxxxxxxxxxxx
      - DB_DATABASE=lychee
      - DB_PORT=3306
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Berlin
    ports:
      - 999:80
    networks:
      home_default:
        ipv4_address: 172.20.0.11
```

### Container logs

```bash
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] 02-default-location: skipped
[migrations] done
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

using keys found in /config/keys
sending incremental file list
./
app/
app/public/
bootstrap/
bootstrap/cache/
debugbar/
framework/
framework/cache/
framework/cache/data/
framework/sessions/
framework/testing/
framework/views/
logs/

sent 787 bytes  received 67 bytes  1,708.00 bytes/sec
total size is 33,116  speedup is 38.78
Connection to mariadb 3306 port [tcp/mysql] succeeded!

In Container.php line 916:
                                             
  Target class [log-viewer] does not exist.  
                                             

In Container.php line 914:
                                     
  Class "log-viewer" does not exist  
                                     

**** The following active confs have different version dates than the samples that are shipped. ****
**** This may be due to user customization or an update to the samples. ****
**** You should compare the following files to the samples in the same folder and update them. ****
**** Use the link at the top of the file to view the changelog. ****
┌────────────┬────────────┬────────────────────────────────────────────────────────────────────────┐
│  old date  │  new date  │ path                                                                   │
├────────────┼────────────┼────────────────────────────────────────────────────────────────────────┤
│ 2021-06-15 │ 2023-04-13 │ /config/nginx/nginx.conf                                               │
│            │ 2023-04-13 │ /config/nginx/site-confs/default.conf                                  │
└────────────┴────────────┴────────────────────────────────────────────────────────────────────────┘
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

**Comment by aptalca** [comment]
Thanks, we're aware and currently working on a fix. 

In the meantime, you can revert to the older version

**Comment by nemchik** [comment]
Potentially fixed in https://github.com/linuxserver/docker-lychee/pull/66
Test image is `lspipepr/lychee:v4.9.2-pkg-e00afaf1-dev-6d0f2974d00214dbca8750aaffb98667e3723ce7-pr-66`

**Comment by netxchanges** [comment]
With the latest update from 9h, issue still present. Any ETA ?

**Comment by Shadow27374** [comment]
No, it is not running.

```bash
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] 02-default-location: skipped
[migrations] done
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

using keys found in /config/keys
sending incremental file list
./
app/
app/public/
bootstrap/
bootstrap/cache/
debugbar/
framework/
framework/cache/
framework/cache/data/
framework/sessions/
framework/testing/
framework/views/
logs/
logs/daily-2023-06-08.log

          9,352 100%    0.00kB/s    0:00:00  
          9,352 100%    0.00kB/s    0:00:00 (xfr#1, to-chk=3/30)
logs/notice-2023-06-08.log

            988 100%  964.84kB/s    0:00:00  
            988 100%  964.84kB/s    0:00:00 (xfr#2, to-chk=1/30)

sent 1,577 bytes  received 109 bytes  3,372.00 bytes/sec
total size is 33,116  speedup is 19.64
Connection to mariadb 3306 port [tcp/mysql] succeeded!

In Container.php line 916:
                                             
  Target class [log-viewer] does not exist.  
                                             

In Container.php line 914:
                                     
  Class "log-viewer" does not exist  
                                     

**** The following active confs have different version dates than the samples that are shipped. ****
**** This may be due to user customization or an update to the samples. ****
**** You should compare the following files to the samples in the same folder and update them. ****
**** Use the link at the top of the file to view the changelog. ****
┌────────────┬────────────┬────────────────────────────────────────────────────────────────────────┐
│  old date  │  new date  │ path                                                                   │
├────────────┼────────────┼────────────────────────────────────────────────────────────────────────┤
│ 2021-06-15 │ 2023-04-13 │ /config/nginx/nginx.conf                                               │
│            │ 2023-04-13 │ /config/nginx/site-confs/default.conf                                  │
└────────────┴────────────┴────────────────────────────────────────────────────────────────────────┘
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

**Comment by ThRPctmylSgltwH** [comment]
I can confirm that the issue remains.

**Comment by ThRPctmylSgltwH** [comment]
**This seems to have been fixed as of the latest version. Thank you!**

[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] 02-default-location: skipped
[migrations] done
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 
   Brought to you by linuxserver.io
───────────────────────────────────────
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1000
User GID:    1000
───────────────────────────────────────
using keys found in /config/keys
**** Make sure the uploads (pictures), sym, and logs folders exist ****
**** Create the symbolic link for the uploads folder ****
cp: not replacing '/pictures/import/index.html'
cp: not replacing '/pictures/medium/index.html'
cp: not replacing '/pictures/small/index.html'
cp: not replacing '/pictures/thumb/index.html'
**** Create the symbolic link for the sym folder ****
**** Create the symbolic link for the logs folder ****
**** Create user.ini for php settings ****
cp: not replacing '/config/user.ini'
Connection to db (172.22.0.2) 3306 port [tcp/mysql] succeeded!
**** Copy the .env to /config ****
**** Inject .env values ****
**** Generate the key (to make sure that cookies cannot be decrypted etc) ****
                                                                                
                           APPLICATION IN PRODUCTION.                           
                                                                                
   WARN  Command canceled.  
**** Migrate the database ****
   INFO  Running migrations.  
  2023_05_15_211448_remove_is_public_album_sorting ................ 149ms DONE
  2023_05_18_103903_bump_version040900 ............................. 18ms DONE
  2023_05_19_131139_bump_version040901 ............................. 17ms DONE
  2023_05_21_225616_bump_version040902 ............................. 17ms DONE
**** Make sure user.css exists and symlink it ****
**** Make sure custom.js exists and symlink it ****
**** Make sure Laravel's log exists ****
**** Set Permissions ****
# do daily/weekly/monthly maintenance
# min   hour    day     month   weekday command
*/15    *       *       *       *       run-parts /etc/periodic/15min
0       *       *       *       *       run-parts /etc/periodic/hourly
0       2       *       *       *       run-parts /etc/periodic/daily
0       3       *       *       6       run-parts /etc/periodic/weekly
0       5       1       *       *       run-parts /etc/periodic/monthly
cp: not replacing '/config/crontabs/root'
* * * * * cd /app/www && php artisan schedule:run >> /dev/null 2>&1
cp: not replacing '/config/crontabs/abc'
**** The following active confs have different version dates than the samples that are shipped. ****
**** This may be due to user customization or an update to the samples. ****
**** You should compare the following files to the samples in the same folder and update them. ****
**** Use the link at the top of the file to view the changelog. ****
┌────────────┬────────────┬────────────────────────────────────────────────────────────────────────┐
│  old date  │  new date  │ path                                                                   │
├────────────┼────────────┼────────────────────────────────────────────────────────────────────────┤
│ 2018-08-16 │ 2023-04-13 │ /config/nginx/nginx.conf                                               │
│            │ 2023-04-13 │ /config/nginx/site-confs/default.conf                                  │
└────────────┴────────────┴────────────────────────────────────────────────────────────────────────┘
[custom-init] No custom files found, skipping...
[ls.io-init] done.

**Comment by Shadow27374** [comment]
Yes, it works!
